databases:
  - name: vivek
    databaseName: vivek
    user: vivek
    plan: free

services:
  - type: web
    name: vivek
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available for paid plan
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vivek
          property: connectionString
      - key: RAILS_MASTER_KEY
      - key: WEB_CONCURRENCY
        value: 2 # sensible_default